/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemGUI.Usuarios;

import SystemGUI.Usuarios.*;
import java.awt.Color;
import controlimpuestos.SystemCRUD.crudUsuarios;
import controlimpuestos.cUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author fanta
 */
public class frmUsuarioCrear extends javax.swing.JPanel {

    //Variables requeridas para obtener los datos del formulario
    private String nombreUsuario, contrasena;

    public frmUsuarioCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h1Registro = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pfContrasena = new javax.swing.JPasswordField();
        tfUsuario = new javax.swing.JTextField();
        jlContrasena = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnCrear = new javax.swing.JPanel();
        jlCrear = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h1Registro.setBackground(new java.awt.Color(21, 14, 48));
        h1Registro.setFont(new java.awt.Font("Roboto", 3, 22)); // NOI18N
        h1Registro.setText("Registro de Usuarios");
        add(h1Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 40));

        jlUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(21, 14, 48));
        jlUsuario.setText("Usuario:");
        add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(21, 14, 48));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 10));

        pfContrasena.setForeground(new java.awt.Color(153, 153, 153));
        pfContrasena.setText("1234567890123456");
        pfContrasena.setBorder(null);
        pfContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfContrasenaFocusGained(evt);
            }
        });
        add(pfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 230, 30));

        tfUsuario.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        tfUsuario.setForeground(new java.awt.Color(153, 153, 153));
        tfUsuario.setText("Ingrese el nombre de usuario");
        tfUsuario.setBorder(null);
        tfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsuarioFocusGained(evt);
            }
        });
        add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 30));

        jlContrasena.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlContrasena.setForeground(new java.awt.Color(21, 14, 48));
        jlContrasena.setText("Contraseña:");
        add(jlContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(21, 14, 48));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, 10));

        btnCrear.setBackground(new java.awt.Color(21, 14, 48));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlCrear.setBackground(new java.awt.Color(21, 14, 48));
        jlCrear.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlCrear.setForeground(new java.awt.Color(255, 255, 255));
        jlCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemGUI/images/newMini.png"))); // NOI18N
        jlCrear.setText("Crear");
        jlCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jlCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCrearMouseClicked
        //Obtener los datos de los campos
        nombreUsuario = tfUsuario.getText();
        contrasena = String.valueOf(pfContrasena.getPassword());
    

        //Validar que los campos no esten vacios
        if (nombreUsuario == "" || nombreUsuario.equals("Ingrese el nombre de usuario")) {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario");
        } else if (contrasena == "" || contrasena.equals("1234567890123456")) {
            JOptionPane.showMessageDialog(null, "Ingrese una contraseña");
        } else {
            //Crear el objeto impuesto
            cUsuarios usuario = new cUsuarios(nombreUsuario, contrasena);

            //Agregar el los datos del objeto usuario a la DB
            try {
                //Instanciar la clase crudUsuarios
                crudUsuarios crud = new crudUsuarios();

                //Llamar al metodo para guardar el impuesto en DB
                crud.guardarUsuario(usuario);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar el usuario.");
            }


            //Limpiar los campos
            tfUsuario.setText("Ingrese el nombre de usuario");
            tfUsuario.setForeground(new Color(153, 153, 153));
            pfContrasena.setText("1234567890123456");
            pfContrasena.setForeground(new Color(153, 153, 153));
            h1Registro.requestFocus();
        }

        

    }//GEN-LAST:event_jlCrearMouseClicked

    private void tfUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsuarioFocusGained
        //Efecto tipo placeholder para el campo Nombre
        if (tfUsuario.getText().equals("Ingrese el nombre de usuario")) {
            tfUsuario.setText("");
            tfUsuario.setForeground(btnCrear.getForeground());
        }
    }//GEN-LAST:event_tfUsuarioFocusGained

    private void pfContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfContrasenaFocusGained
        // TODO add your handling code here:
        if (String.valueOf(pfContrasena.getPassword()).equals("1234567890123456")) {
            pfContrasena.setText("");
            pfContrasena.setForeground(btnCrear.getForeground());
        }
    }//GEN-LAST:event_pfContrasenaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCrear;
    private javax.swing.JLabel h1Registro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlContrasena;
    private javax.swing.JLabel jlCrear;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField pfContrasena;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
