/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemGUI.Pagos;

import SystemGUI.Impuesto.*;
import SystemGUI.Clientes.*;
import java.awt.BorderLayout;

/**
 *
 * @author fanta
 */
public class frmPagos extends javax.swing.JPanel {

    /**
     * Creates new form frmClientes
     */
    public frmPagos() {
        initComponents();
        crearPago.setVisible(true);
        buscarPago.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        divisor = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JPanel();
        jlBusqueda = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JPanel();
        jlRegistro = new javax.swing.JLabel();
        jpDynamic = new javax.swing.JPanel();
        crearPago = new javax.swing.JPanel();
        frmPagosCrear1 = new SystemGUI.Pagos.frmPagosCrear();
        buscarPago = new javax.swing.JPanel();
        frmPagosBuscar1 = new SystemGUI.Pagos.frmPagosBuscar();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        divisor.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout divisorLayout = new javax.swing.GroupLayout(divisor);
        divisor.setLayout(divisorLayout);
        divisorLayout.setHorizontalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        divisorLayout.setVerticalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        bg.add(divisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 600));

        header.setBackground(new java.awt.Color(221, 221, 221));

        btnBusqueda.setBackground(new java.awt.Color(21, 14, 48));
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jlBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jlBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBusqueda.setText("Búsqueda");
        jlBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBusquedaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBusquedaLayout = new javax.swing.GroupLayout(btnBusqueda);
        btnBusqueda.setLayout(btnBusquedaLayout);
        btnBusquedaLayout.setHorizontalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnBusquedaLayout.setVerticalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnRegistro.setBackground(new java.awt.Color(21, 14, 48));
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jlRegistro.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jlRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRegistro.setText("Registro");
        jlRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegistroLayout = new javax.swing.GroupLayout(btnRegistro);
        btnRegistro.setLayout(btnRegistroLayout);
        btnRegistroLayout.setHorizontalGroup(
            btnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnRegistroLayout.setVerticalGroup(
            btnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jpDynamic.setLayout(new java.awt.CardLayout());

        crearPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        crearPago.add(frmPagosCrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        jpDynamic.add(crearPago, "card2");

        buscarPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        buscarPago.add(frmPagosBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        jpDynamic.add(buscarPago, "card3");

        bg.add(jpDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 560));

        add(bg, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jlBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBusquedaMouseClicked
        // TODO add your handling code here:
        
        crearPago.setVisible(false);
        buscarPago.setVisible(true);
    }//GEN-LAST:event_jlBusquedaMouseClicked

    private void jlRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroMouseClicked
        // TODO add your handling code here:
        crearPago.setVisible(true);
        buscarPago.setVisible(false);
    }//GEN-LAST:event_jlRegistroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnBusqueda;
    private javax.swing.JPanel btnRegistro;
    private javax.swing.JPanel buscarPago;
    private javax.swing.JPanel crearPago;
    private javax.swing.JPanel divisor;
    private SystemGUI.Pagos.frmPagosBuscar frmPagosBuscar1;
    private SystemGUI.Pagos.frmPagosCrear frmPagosCrear1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jlBusqueda;
    private javax.swing.JLabel jlRegistro;
    private javax.swing.JPanel jpDynamic;
    // End of variables declaration//GEN-END:variables
}
