/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemGUI;

import SystemGUI.Clientes.*;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author fanta
 */
public class frmMenu extends javax.swing.JFrame {

    public JPanel parentDynamic;
    /**
     * Creates new form frmClientes
     */
    public frmMenu() {
        initComponents();
        mainLogo.requestFocusInWindow(); //Metodo para darle el foco al logo y evitar que el textField se seleccione al iniciar
        
        frmClientesCrear clientesCrear = new frmClientesCrear();
        clientesCrear.setSize(630, 560);
        clientesCrear.setLocation(0, 0);

        jpDynamic.removeAll();
        jpDynamic.add(clientesCrear, BorderLayout.CENTER);
        jpDynamic.revalidate();
        jpDynamic.repaint();
    }
    
    public JPanel getParentPanel() {
        return parentDynamic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jpSideMenu = new javax.swing.JPanel();
        mainLogo = new javax.swing.JLabel();
        nombreSistema = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        jlClientes = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JPanel();
        jlEmpleados = new javax.swing.JLabel();
        btnImpuestos = new javax.swing.JPanel();
        jlImpuestos = new javax.swing.JLabel();
        btnPagos = new javax.swing.JPanel();
        jlPagos = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        jlUsuarios = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jlLogout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        divisor = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JPanel();
        jlBusqueda = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JPanel();
        jlRegistro = new javax.swing.JLabel();
        jpDynamic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSideMenu.setBackground(new java.awt.Color(21, 14, 48));
        jpSideMenu.setPreferredSize(new java.awt.Dimension(220, 600));

        mainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemGUI/images/mainLogo.png"))); // NOI18N

        nombreSistema.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        nombreSistema.setForeground(new java.awt.Color(255, 255, 255));
        nombreSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreSistema.setText("¡Bienvenido!");

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlClientes.setBackground(new java.awt.Color(255, 255, 255));
        jlClientes.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlClientes.setForeground(new java.awt.Color(21, 14, 48));
        jlClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlClientes.setText("Clientes");

        javax.swing.GroupLayout btnClientesLayout = new javax.swing.GroupLayout(btnClientes);
        btnClientes.setLayout(btnClientesLayout);
        btnClientesLayout.setHorizontalGroup(
            btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClientesLayout.createSequentialGroup()
                .addComponent(jlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnClientesLayout.setVerticalGroup(
            btnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        jlEmpleados.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlEmpleados.setForeground(new java.awt.Color(21, 14, 48));
        jlEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEmpleados.setText("Empleados");

        javax.swing.GroupLayout btnEmpleadosLayout = new javax.swing.GroupLayout(btnEmpleados);
        btnEmpleados.setLayout(btnEmpleadosLayout);
        btnEmpleadosLayout.setHorizontalGroup(
            btnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmpleadosLayout.createSequentialGroup()
                .addComponent(jlEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEmpleadosLayout.setVerticalGroup(
            btnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnImpuestos.setBackground(new java.awt.Color(255, 255, 255));
        btnImpuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlImpuestos.setBackground(new java.awt.Color(255, 255, 255));
        jlImpuestos.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlImpuestos.setForeground(new java.awt.Color(21, 14, 48));
        jlImpuestos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImpuestos.setText("Impuestos");

        javax.swing.GroupLayout btnImpuestosLayout = new javax.swing.GroupLayout(btnImpuestos);
        btnImpuestos.setLayout(btnImpuestosLayout);
        btnImpuestosLayout.setHorizontalGroup(
            btnImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImpuestosLayout.createSequentialGroup()
                .addComponent(jlImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnImpuestosLayout.setVerticalGroup(
            btnImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImpuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnPagos.setBackground(new java.awt.Color(255, 255, 255));
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlPagos.setBackground(new java.awt.Color(255, 255, 255));
        jlPagos.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlPagos.setForeground(new java.awt.Color(21, 14, 48));
        jlPagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPagos.setText("Pagos");

        javax.swing.GroupLayout btnPagosLayout = new javax.swing.GroupLayout(btnPagos);
        btnPagos.setLayout(btnPagosLayout);
        btnPagosLayout.setHorizontalGroup(
            btnPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPagosLayout.createSequentialGroup()
                .addComponent(jlPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnPagosLayout.setVerticalGroup(
            btnPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jlUsuarios.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlUsuarios.setForeground(new java.awt.Color(21, 14, 48));
        jlUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlUsuarios.setText("Usuarios");

        javax.swing.GroupLayout btnUsuariosLayout = new javax.swing.GroupLayout(btnUsuarios);
        btnUsuarios.setLayout(btnUsuariosLayout);
        btnUsuariosLayout.setHorizontalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addComponent(jlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnUsuariosLayout.setVerticalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnLogout.setBackground(new java.awt.Color(21, 14, 48));
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemGUI/images/logout.png"))); // NOI18N

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpSideMenuLayout = new javax.swing.GroupLayout(jpSideMenu);
        jpSideMenu.setLayout(jpSideMenuLayout);
        jpSideMenuLayout.setHorizontalGroup(
            jpSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnImpuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpSideMenuLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpSideMenuLayout.createSequentialGroup()
                .addGroup(jpSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombreSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(mainLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpSideMenuLayout.setVerticalGroup(
            jpSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSideMenuLayout.createSequentialGroup()
                .addGroup(jpSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSideMenuLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(nombreSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        bg.add(jpSideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        divisor.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout divisorLayout = new javax.swing.GroupLayout(divisor);
        divisor.setLayout(divisorLayout);
        divisorLayout.setHorizontalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        divisorLayout.setVerticalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        bg.add(divisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 5, 600));

        header.setBackground(new java.awt.Color(221, 221, 221));

        btnBusqueda.setBackground(new java.awt.Color(21, 14, 48));
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jlBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jlBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBusqueda.setText("Búsqueda");
        jlBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBusquedaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBusquedaLayout = new javax.swing.GroupLayout(btnBusqueda);
        btnBusqueda.setLayout(btnBusquedaLayout);
        btnBusquedaLayout.setHorizontalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnBusquedaLayout.setVerticalGroup(
            btnBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnRegistro.setBackground(new java.awt.Color(21, 14, 48));
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jlRegistro.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jlRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRegistro.setText("Registro");
        jlRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegistroLayout = new javax.swing.GroupLayout(btnRegistro);
        btnRegistro.setLayout(btnRegistroLayout);
        btnRegistroLayout.setHorizontalGroup(
            btnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnRegistroLayout.setVerticalGroup(
            btnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 630, 40));

        jpDynamic.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpDynamicLayout = new javax.swing.GroupLayout(jpDynamic);
        jpDynamic.setLayout(jpDynamicLayout);
        jpDynamicLayout.setHorizontalGroup(
            jpDynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jpDynamicLayout.setVerticalGroup(
            jpDynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        bg.add(jpDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 630, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBusquedaMouseClicked
        // TODO add your handling code here:
        frmClientesBuscar clientesBuscar = new frmClientesBuscar();
        clientesBuscar.setSize(630, 560);
        clientesBuscar.setLocation(0, 0);

        jpDynamic.removeAll();
        jpDynamic.add(clientesBuscar, BorderLayout.CENTER);
        jpDynamic.revalidate();
        jpDynamic.repaint();
    }//GEN-LAST:event_jlBusquedaMouseClicked

    private void jlRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroMouseClicked
        // TODO add your handling code here:
        frmClientesCrear clientesCrear = new frmClientesCrear();
        clientesCrear.setSize(630, 560);
        clientesCrear.setLocation(0, 0);

        jpDynamic.removeAll();
        jpDynamic.add(clientesCrear, BorderLayout.CENTER);
        jpDynamic.revalidate();
        jpDynamic.repaint();
    }//GEN-LAST:event_jlRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnBusqueda;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnEmpleados;
    private javax.swing.JPanel btnImpuestos;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnPagos;
    private javax.swing.JPanel btnRegistro;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JPanel divisor;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlBusqueda;
    private javax.swing.JLabel jlClientes;
    private javax.swing.JLabel jlEmpleados;
    private javax.swing.JLabel jlImpuestos;
    private javax.swing.JLabel jlLogout;
    private javax.swing.JLabel jlPagos;
    private javax.swing.JLabel jlRegistro;
    private javax.swing.JLabel jlUsuarios;
    private javax.swing.JPanel jpDynamic;
    private javax.swing.JPanel jpSideMenu;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel nombreSistema;
    // End of variables declaration//GEN-END:variables
}
